In [9]:
import os
from glob import glob #filename pattern matching module
import xlrd
import openpyxl 
import datetime as dt
from datetime import datetime as dt
from datetime import timedelta as td
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sns

In [10]:
os.getcwd()

'D:\\Desktop\\travail_workspace\\ETL_workspace'

In [13]:
# files_path = glob("C:\\Users\\buche\\Desktop\\travail_workspace\\cash_withdraw\\0825-0906\\withdrawRecord_*.xlsx")
files_path = glob("D:\\Desktop\\travail_workspace\\cash_withdraw\\0825-0907\\withdrawRecord_*.xlsx")

g = pd.DataFrame()
for file in files_path:
    df = pd.read_excel(file, engine='openpyxl')
    g = g.append(df, ignore_index=True)
    
# g.to_csv('C:\\Users\\buche\\Desktop\\travail_workspace\\cash_withdraw\\withdraw_test.csv', encoding = 'utf-8-sig')
g.to_csv('D:\\Desktop\\travail_workspace\\cash_withdraw\\withdraw_test.csv', encoding = 'utf-8-sig')

C:\Users\chanm\AppData\Local\Temp\ipykernel_17208\20849245.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  g = g.append(df, ignore_index=True)
C:\Users\chanm\AppData\Local\Temp\ipykernel_17208\20849245.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  g = g.append(df, ignore_index=True)

In [14]:
k=g

In [15]:
k.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3155 entries, 0 to 3154
Data columns (total 23 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   用户ID     3155 non-null   int64
 1   用户名      3142 non-null   object
 2   用户手机号    3155 non-null   int64
 3   订单号      3155 non-null   object
 4   渠道订单号    3155 non-null   int64
 5   提现金额     3155 non-null   float64
 6   实际到账金额   3155 non-null   float64
 7   银行名称     3155 non-null   object
 8   银行卡号     3155 non-null   int64
 9   提现类型     3155 non-null   int64
 10  提现渠道ID   3155 non-null   int64
 11  提现状态     3155 non-null   int64
 12  审核未通过原因  0 non-null      float64
 13  审核完成时间   3155 non-null   object
 14  提现完成时间   3155 non-null   object
 15  用户手机系统   3155 non-null   int64
 16  用户渠道来源   0 non-null      float64
 17  用户应用来源   3155 non-null   int64
 18  ip地址     3155 non-null   object
 19  地区       0 non-null      float64
 20  设备ID     3155 non-null   object
 21  创建时间     3155 non-null   object
 22  审核状态     3155 non-null   int64
dtypes: float64(5), int64(10), object(8)
memory usage: 567.0+ KB

In [16]:
(k.isna()).count()

用户ID       3155
用户名        3155
用户手机号      3155
订单号        3155
渠道订单号      3155
提现金额       3155
实际到账金额     3155
银行名称       3155
银行卡号       3155
提现类型       3155
提现渠道ID     3155
提现状态       3155
审核未通过原因    3155
审核完成时间     3155
提现完成时间     3155
用户手机系统     3155
用户渠道来源     3155
用户应用来源     3155
ip地址       3155
地区         3155
设备ID       3155
创建时间       3155
审核状态       3155
dtype: int64

In [17]:
k[k.duplicated()]

Empty DataFrame
Columns: [用户ID, 用户名, 用户手机号, 订单号, 渠道订单号, 提现金额, 实际到账金额, 银行名称, 银行卡号, 提现类型, 提现渠道ID, 提现状态, 审核未通过原因, 审核完成时间, 提现完成时间, 用户手机系统, 用户渠道来源, 用户应用来源, ip地址, 地区, 设备ID, 创建时间, 审核状态]
Index: []

[0 rows x 23 columns]

In [52]:
k.drop_duplicates(inplace=True)

In [18]:
k.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3155 entries, 0 to 3154
Data columns (total 23 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   用户ID     3155 non-null   int64
 1   用户名      3142 non-null   object
 2   用户手机号    3155 non-null   int64
 3   订单号      3155 non-null   object
 4   渠道订单号    3155 non-null   int64
 5   提现金额     3155 non-null   float64
 6   实际到账金额   3155 non-null   float64
 7   银行名称     3155 non-null   object
 8   银行卡号     3155 non-null   int64
 9   提现类型     3155 non-null   int64
 10  提现渠道ID   3155 non-null   int64
 11  提现状态     3155 non-null   int64
 12  审核未通过原因  0 non-null      float64
 13  审核完成时间   3155 non-null   object
 14  提现完成时间   3155 non-null   object
 15  用户手机系统   3155 non-null   int64
 16  用户渠道来源   0 non-null      float64
 17  用户应用来源   3155 non-null   int64
 18  ip地址     3155 non-null   object
 19  地区       0 non-null      float64
 20  设备ID     3155 non-null   object
 21  创建时间     3155 non-null   object
 22  审核状态     3155 non-null   int64
dtypes: float64(5), int64(10), object(8)
memory usage: 567.0+ KB

In [20]:
k['提现金额2'] = k['提现金额']

In [21]:
k["提现完成时间"] = pd.to_datetime(k["提现完成时间"])
k["时间"] = k["提现完成时间"].apply(lambda x: x.strftime('%m-%d'))

In [31]:
k_p = pd.pivot_table(k, index=["用户ID"], aggfunc={"提现金额": ['count', 'min', 'max', np.sum,]})

In [32]:
k_p

          提现金额
         count      max     min       sum
用户ID
335929       1   500.00  500.00    500.00
426659       1   300.00  300.00    300.00
511600       1   205.03  205.03    205.03
574633       8  5000.00  344.72  21277.86
623981       1   200.00  200.00    200.00
...        ...      ...     ...       ...
50584179     1   717.40  717.40    717.40
50620875     1   208.64  208.64    208.64
50625754     2   300.00  200.00    500.00
50665792     1   509.10  509.10    509.10
50692575     1   303.00  303.00    303.00

[1216 rows x 4 columns]

In [28]:
# k_p = pd.DataFrame(k_p)

## dataframe pivot

In [9]:
t = all_top_up.iloc[:, [0, 1, 2, 3, 9, 11]]
t = t.reset_index()
t.head()

,index,订单发起时间,订单完成时间,用户id,用户昵称,支付类型,充值金额
0,0,2023-08-30 23:58:45,2023-08-30 23:58:57,46500141,外阐绘,支付宝支付,200.0
1,1,2023-08-30 23:58:21,2023-08-30 23:58:57,30139753,叙利亚乌鸡哥,支付宝支付,50.0
2,2,2023-08-30 23:58:06,2023-08-30 23:58:44,43014382,志咆犁,支付宝支付,200.0
3,3,2023-08-30 23:56:45,2023-08-30 23:57:05,30585311,逗比,QQ钱包,100.0
4,4,2023-08-30 23:56:30,2023-08-30 23:57:15,14637152,锡物言,微信支付,200.0

In [10]:
# 確認資料完整
print(t.isna().sum())
print(t.info())

index      0
订单发起时间     0
订单完成时间     0
用户id       0
用户昵称      62
支付类型       0
充值金额       0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18071 entries, 0 to 18070
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   18071 non-null  int64
 1   订单发起时间  18071 non-null  object
 2   订单完成时间  18071 non-null  object
 3   用户id    18071 non-null  int64
 4   用户昵称    18009 non-null  object
 5   支付类型    18071 non-null  object
 6   充值金额    18071 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 988.4+ KB
None

In [11]:
mv = t[t.isna().values==True]
print(mv.info())
print(mv[mv.duplicated()])
mv

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 486 to 17364
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   62 non-null     int64
 1   订单发起时间  62 non-null     object
 2   订单完成时间  62 non-null     object
 3   用户id    62 non-null     int64
 4   用户昵称    0 non-null      object
 5   支付类型    62 non-null     object
 6   充值金额    62 non-null     float64
dtypes: float64(1), int64(2), object(4)
memory usage: 3.9+ KB
None
Empty DataFrame
Columns: [index, 订单发起时间, 订单完成时间, 用户id, 用户昵称, 支付类型, 充值金额]
Index: []

,index,订单发起时间,订单完成时间,用户id,用户昵称,支付类型,充值金额
486,486,2023-08-30 20:06:26,2023-08-30 20:07:16,27000989,NaN,微信支付,50.0
639,639,2023-08-30 18:28:13,2023-08-30 18:28:41,27000989,NaN,微信支付,50.0
705,705,2023-08-30 17:51:49,2023-08-30 17:52:45,27000989,NaN,微信支付,50.0
2352,2352,2023-08-31 22:04:23,2023-08-31 22:05:15,47638574,NaN,微信支付,200.0
2445,2445,2023-08-31 21:28:26,2023-08-31 21:28:58,41482976,NaN,支付宝支付,50.0
...,...,...,...,...,...,...,...
16968,16968,2023-09-06 13:29:57,2023-09-06 13:30:26,41482976,NaN,QQ钱包,100.0
16981,16981,2023-09-06 13:22:43,2023-09-06 13:23:20,41482976,NaN,QQ钱包,100.0
17150,17150,2023-09-06 11:42:51,2023-09-06 11:43:37,41482976,NaN,QQ钱包,100.0
17198,17198,2023-09-06 11:23:15,2023-09-06 11:24:06,38880646,NaN,支付宝支付,50.0
17364,17364,2023-09-06 09:57:35,2023-09-06 09:58:06,38880646,NaN,微信支付,50.0

In [12]:
t.drop_duplicates(inplace=True)

In [13]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18071 entries, 0 to 18070
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   18071 non-null  int64
 1   订单发起时间  18071 non-null  object
 2   订单完成时间  18071 non-null  object
 3   用户id    18071 non-null  int64
 4   用户昵称    18009 non-null  object
 5   支付类型    18071 non-null  object
 6   充值金额    18071 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 1.1+ MB

In [14]:
# 以['订单完成时间']為基準
def splitname(x):
    x=str(x)
    return x[0:10]
li_tmp = t["订单发起时间"]
print(type(li_tmp))

<class 'pandas.core.series.Series'>

In [15]:
li_tmp = pd.Series(li_tmp)
print(type(li_tmp))

<class 'pandas.core.series.Series'>

In [16]:
li_tmp = list(map(splitname,list(li_tmp)))
# print(len(li_tmp))

In [17]:
t["订单发起时间2"] = li_tmp

In [18]:
t["订单发起时间2"]= pd.to_datetime(t["订单发起时间2"])
t["订单发起时间2"] = t["订单发起时间2"].apply(lambda x: x.strftime('%m-%d'))
t.rename(columns = {"订单发起时间2":"日期"}, inplace=True)

In [19]:
t['用户id'] = t['用户id'].astype(str)

In [20]:
t.loc[11670:11672,:] # ?? 為什麼重複項自己不見?????

,index,订单发起时间,订单完成时间,用户id,用户昵称,支付类型,充值金额,日期
11670,11670,2023-09-04 21:21:16,2023-09-04 21:22:06,2143356,一把定输赢,支付宝支付,50.0,09-04
11671,11671,2023-09-04 21:20:28,2023-09-04 21:22:10,43810824,辕瓜陋,支付宝支付,500.0,09-04
11672,11672,2023-09-04 21:20:22,2023-09-04 21:20:46,36879143,你爸爸,微信支付,50.0,09-04

In [21]:
len(t)

18071

In [22]:
manual_0831= t[(t["日期"] == '08-31')&(t["支付类型"] == '人工支付')]
manual_0831.to_csv('C:\\Users\\buche\\Desktop\\travail_workspace\\top_up_analysis\\top_up_report\\manual_0831.csv', encoding = 'utf-8-sig')

# 偵錯??["用户id"]["用户昵称"]不一致 ????

In [23]:
dul_id_test = t

In [24]:
print(len(dul_id_test["用户id"].unique()))
print(len(dul_id_test["用户昵称"].unique()))

3727
3741

In [25]:
# 合併id、暱稱字串
dul_id_test["id_name"] = dul_id_test["用户id"].str.cat(dul_id_test["用户昵称"], sep=',')

In [26]:
print(len(t["id_name"].unique()))

3744

In [27]:
## 有可能是1個id在一天內更改暱稱，並用不同暱稱儲值?? 
## 或是不同暱稱可以共用一個id　
## 做pivot的時候 統一用id

In [28]:
dul_id_test = dul_id_test.sort_values(by=["日期","用户id"])

In [29]:
dul_id_test

,index,订单发起时间,订单完成时间,用户id,用户昵称,支付类型,充值金额,日期,id_name
767,767,2023-08-30 17:16:39,2023-08-30 17:17:15,10174024,粒吴沧,微信支付,200.0,08-30,"10174024,粒吴沧"
799,799,2023-08-30 16:54:24,2023-08-30 16:56:29,10344689,酶肾涅,微信支付,200.0,08-30,"10344689,酶肾涅"
812,812,2023-08-30 16:48:04,2023-08-30 16:50:39,10344689,酶肾涅,微信支付,200.0,08-30,"10344689,酶肾涅"
1104,1104,2023-08-30 13:59:19,2023-08-30 14:00:15,10382312,葫芦娃,支付宝支付,50.0,08-30,"10382312,葫芦娃"
1200,1200,2023-08-30 13:07:22,2023-08-30 13:08:15,10382312,葫芦娃,支付宝支付,50.0,08-30,"10382312,葫芦娃"
...,...,...,...,...,...,...,...,...,...
16643,16643,2023-09-06 16:40:13,2023-09-06 16:40:44,9667294,么背耐,支付宝支付,100.0,09-06,"9667294,么背耐"
16685,16685,2023-09-06 16:12:54,2023-09-06 16:13:14,9667294,么背耐,微信支付,100.0,09-06,"9667294,么背耐"
16699,16699,2023-09-06 16:02:50,2023-09-06 16:03:23,9667294,么背耐,微信支付,100.0,09-06,"9667294,么背耐"
16682,16682,2023-09-06 16:15:32,2023-09-06 16:17:06,968147,胳傲痰,支付宝支付,50.0,09-06,"968147,胳傲痰"
15920,15920,2023-09-06 23:48:28,2023-09-06 23:49:00,9773528,孺渺揽,支付宝支付,100.0,09-06,"9773528,孺渺揽"

In [30]:
print(len(dul_id_test[dul_id_test["日期"]=='08-27']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='08-27']["用户昵称"].unique()))

0
0

In [31]:
print(len(dul_id_test[dul_id_test["日期"]=='08-28']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='08-28']["用户昵称"].unique()))

0
0

In [32]:
print(len(dul_id_test[dul_id_test["日期"]=='08-29']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='08-29']["用户昵称"].unique()))

0
0

In [33]:
print(len(dul_id_test[dul_id_test["日期"]=='08-30']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='08-30']["用户昵称"].unique()))

761
761

In [34]:
print(len(dul_id_test[dul_id_test["日期"]=='08-31']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='08-31']["用户昵称"].unique()))

768
767

In [35]:
print(len(dul_id_test[dul_id_test["日期"]=='09-01']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='09-01']["用户昵称"].unique()))

881
880

In [36]:
print(len(dul_id_test[dul_id_test["日期"]=='09-02']["用户id"].unique()))
print(len(dul_id_test[dul_id_test["日期"]=='09-02']["用户昵称"].unique()))

852
851

In [37]:
dul_id_test

,index,订单发起时间,订单完成时间,用户id,用户昵称,支付类型,充值金额,日期,id_name
767,767,2023-08-30 17:16:39,2023-08-30 17:17:15,10174024,粒吴沧,微信支付,200.0,08-30,"10174024,粒吴沧"
799,799,2023-08-30 16:54:24,2023-08-30 16:56:29,10344689,酶肾涅,微信支付,200.0,08-30,"10344689,酶肾涅"
812,812,2023-08-30 16:48:04,2023-08-30 16:50:39,10344689,酶肾涅,微信支付,200.0,08-30,"10344689,酶肾涅"
1104,1104,2023-08-30 13:59:19,2023-08-30 14:00:15,10382312,葫芦娃,支付宝支付,50.0,08-30,"10382312,葫芦娃"
1200,1200,2023-08-30 13:07:22,2023-08-30 13:08:15,10382312,葫芦娃,支付宝支付,50.0,08-30,"10382312,葫芦娃"
...,...,...,...,...,...,...,...,...,...
16643,16643,2023-09-06 16:40:13,2023-09-06 16:40:44,9667294,么背耐,支付宝支付,100.0,09-06,"9667294,么背耐"
16685,16685,2023-09-06 16:12:54,2023-09-06 16:13:14,9667294,么背耐,微信支付,100.0,09-06,"9667294,么背耐"
16699,16699,2023-09-06 16:02:50,2023-09-06 16:03:23,9667294,么背耐,微信支付,100.0,09-06,"9667294,么背耐"
16682,16682,2023-09-06 16:15:32,2023-09-06 16:17:06,968147,胳傲痰,支付宝支付,50.0,09-06,"968147,胳傲痰"
15920,15920,2023-09-06 23:48:28,2023-09-06 23:49:00,9773528,孺渺揽,支付宝支付,100.0,09-06,"9773528,孺渺揽"

In [38]:
# 顯示不重複的id_name
dul_id_unique = pd.unique(dul_id_test["id_name"])
dul_id_unique

array(['10174024,粒吴沧', '10344689,酶肾涅', '10382312,葫芦娃', ..., '869416,翻固师',
       '8781517,抱佛脚', '9667294,么背耐'], dtype=object)

In [39]:
dul_id_test[dul_id_test.duplicated()]

Empty DataFrame
Columns: [index, 订单发起时间, 订单完成时间, 用户id, 用户昵称, 支付类型, 充值金额, 日期, id_name]
Index: []

In [40]:
# 顯示重複的id_name
if len(dul_id_test[dul_id_test.duplicated()])==0:
    print('無重複')

無重複

In [41]:
#dul_id_test.loc[11671:11672,:]

## create pivot tb

In [42]:
t['充值金额2'] = t['充值金额']

In [43]:
# dd = pd.pivot_table(t, index=["支付类型", "日期"], values=["充值金额", "充值金额2", "充值金额3"], aggfunc=[np.sum])
# dd

In [44]:
pivot_t = pd.pivot_table(t, index=["支付类型", "日期"], aggfunc={"充值金额": np.sum , "充值金额2": 'count', "用户id": pd.Series.nunique})
#　margins=True

In [45]:
pivot_t.columns
pivot_t

                 充值金额  充值金额2  用户id
支付类型  日期
QQ钱包  08-30   16900.0    115    48
      08-31   15900.0    100    50
      09-01   17800.0    122    50
      09-02   16800.0    111    38
      09-03   13600.0     90    37
      09-04   23400.0    156    44
      09-05   23600.0    142    49
      09-06   23000.0    146    44
云闪付   08-30    3600.0     18    10
      08-31    2400.0     12     5
      09-01    1800.0      9     7
      09-02     600.0      3     3
      09-03    1600.0      8     7
      09-04    2000.0     10     8
      09-05     800.0      4     3
      09-06     200.0      1     1
人工支付  08-30   48200.0     29    14
      08-31   71700.0     28    17
      09-01   82000.0     42    19
      09-02   34900.0     22    15
      09-03   26200.0     18    12
      09-04  113900.1     32    16
      09-05   71800.0     30    14
      09-06  116000.0     53    25
微信支付  08-30   53000.0    559   331
      08-31   45200.0    499   300
      09-01   50350.0    538   371
      09-02   57950.0    636   392
      09-03   61950.0    634   345
      09-04   60400.0    587   290
      09-05   45000.0    435   252
      09-06   36900.0    428   259
支付宝支付 08-30  401350.0   1360   483
      08-31  358950.0   1451   506
      09-01  330350.0   1547   548
      09-02  349000.0   1527   514
      09-03  411500.0   1584   521
      09-04  355200.0   1530   516
      09-05  335350.0   1533   509
      09-06  291200.0   1469   495
银行卡支付 08-30   38500.0     44    24
      08-31   33500.0     45    29
      09-01   82000.0     86    45
      09-02   47500.0     51    29
      09-03   44500.0     47    28
      09-04   41000.0     45    23
      09-05   72000.0     65    39
      09-06  100500.0     70    31

In [46]:
pivot_t['mean_order'] = round(pivot_t['充值金额']/pivot_t['充值金额2'], 2)
pivot_t['mean_person'] = round(pivot_t['充值金额']/pivot_t['用户id'], 2)
pivot_t['amount_dod'] = pd.Series(pivot_t['充值金额']).pct_change().apply(lambda x: format(x, '.2%')) # 區分支付類型
pivot_t['order_dod'] = pd.Series(pivot_t['充值金额2']).pct_change().apply(lambda x: format(x, '.2%')) # 區分支付類型
pivot_t['person_dod'] = pd.Series(pivot_t['用户id']).pct_change().apply(lambda x: format(x, '.2%')) # 區分支付類型
pivot_t['mean_order_dod'] = pd.Series(pivot_t['mean_order']).pct_change().apply(lambda x: format(x, '.2%')) # 區分支付類型
pivot_t['mean_person_dod'] = pd.Series(pivot_t['mean_person']).pct_change().apply(lambda x: format(x, '.2%')) # 區分支付類型

In [47]:
pivot_t = pivot_t.reset_index()

In [48]:
# # 刪掉多的那天
# d = [pivot_t.iloc[0,1]]
# unused = pivot_t['日期'].isin(d)
# pivot_t = pivot_t[-unused]

In [49]:
pivot_t

,支付类型,日期,充值金额,充值金额2,用户id,mean_order,mean_person,amount_dod,order_dod,person_dod,mean_order_dod,mean_person_dod
0,QQ钱包,08-30,16900.0,115,48,146.96,352.08,nan%,nan%,nan%,nan%,nan%
1,QQ钱包,08-31,15900.0,100,50,159.00,318.00,-5.92%,-13.04%,4.17%,8.19%,-9.68%
2,QQ钱包,09-01,17800.0,122,50,145.90,356.00,11.95%,22.00%,0.00%,-8.24%,11.95%
3,QQ钱包,09-02,16800.0,111,38,151.35,442.11,-5.62%,-9.02%,-24.00%,3.74%,24.19%
4,QQ钱包,09-03,13600.0,90,37,151.11,367.57,-19.05%,-18.92%,-2.63%,-0.16%,-16.86%
5,QQ钱包,09-04,23400.0,156,44,150.00,531.82,72.06%,73.33%,18.92%,-0.73%,44.69%
6,QQ钱包,09-05,23600.0,142,49,166.20,481.63,0.85%,-8.97%,11.36%,10.80%,-9.44%
7,QQ钱包,09-06,23000.0,146,44,157.53,522.73,-2.54%,2.82%,-10.20%,-5.22%,8.53%
8,云闪付,08-30,3600.0,18,10,200.00,360.00,-84.35%,-87.67%,-77.27%,26.96%,-31.13%
9,云闪付,08-31,2400.0,12,5,200.00,480.00,-33.33%,-33.33%,-50.00%,0.00%,33.33%
10,云闪付,09-01,1800.0,9,7,200.00,257.14,-25.00%,-25.00%,40.00%,0.00%,-46.43%
11,云闪付,09-02,600.0,3,3,200.00,200.00,-66.67%,-66.67%,-57.14%,0.00%,-22.22%
12,云闪付,09-03,1600.0,8,7,200.00,228.57,166.67%,166.67%,133.33%,0.00%,14.28%
13,云闪付,09-04,2000.0,10,8,200.00,250.00,25.00%,25.00%,14.29%,0.00%,9.38%
14,云闪付,09-05,800.0,4,3,200.00,266.67,-60.00%,-60.00%,-62.50%,0.00%,6.67%
15,云闪付,09-06,200.0,1,1,200.00,200.00,-75.00%,-75.00%,-66.67%,0.00%,-25.00%
16,人工支付,08-30,48200.0,29,14,1662.07,3442.86,24000.00%,2800.00%,1300.00%,731.03%,1621.43%
17,人工支付,08-31,71700.0,28,17,2560.71,4217.65,48.76%,-3.45%,21.43%,54.07%,22.50%
18,人工支付,09-01,82000.0,42,19,1952.38,4315.79,14.37%,50.00%,11.76%,-23.76%,2.33%
19,人工支付,09-02,34900.0,22,15,1586.36,2326.67,-57.44%,-47.62%,-21.05%,-18.75%,-46.09%
20,人工支付,09-03,26200.0,18,12,1455.56,2183.33,-24.93%,-18.18%,-20.00%,-8.25%,-6.16%
21,人工支付,09-04,113900.1,32,16,3559.38,7118.76,334.73%,77.78%,33.33%,144.54%,226.05%
22,人工支付,09-05,71800.0,30,14,2393.33,5128.57,-36.96%,-6.25%,-12.50%,-32.76%,-27.96%
23,人工支付,09-06,116000.0,53,25,2188.68,4640.00,61.56%,76.67%,78.57%,-8.55%,-9.53%
24,微信支付,08-30,53000.0,559,331,94.81,160.12,-54.31%,954.72%,1224.00%,-95.67%,-96.55%
25,微信支付,08-31,45200.0,499,300,90.58,150.67,-14.72%,-10.73%,-9.37%,-4.46%,-5.90%
26,微信支付,09-01,50350.0,538,371,93.59,135.71,11.39%,7.82%,23.67%,3.32%,-9.93%
27,微信支付,09-02,57950.0,636,392,91.12,147.83,15.09%,18.22%,5.66%,-2.64%,8.93%
28,微信支付,09-03,61950.0,634,345,97.71,179.57,6.90%,-0.31%,-11.99%,7.23%,21.47%
29,微信支付,09-04,60400.0,587,290,102.90,208.28,-2.50%,-7.41%,-15.94%,5.31%,15.99%
30,微信支付,09-05,45000.0,435,252,103.45,178.57,-25.50%,-25.89%,-13.10%,0.53%,-14.26%
31,微信支付,09-06,36900.0,428,259,86.21,142.47,-18.00%,-1.61%,2.78%,-16.67%,-20.22%
32,支付宝支付,08-30,401350.0,1360,483,295.11,830.95,987.67%,217.76%,86.49%,242.32%,483.25%
33,支付宝支付,08-31,358950.0,1451,506,247.38,709.39,-10.56%,6.69%,4.76%,-16.17%,-14.63%
34,支付宝支付,09-01,330350.0,1547,548,213.54,602.83,-7.97%,6.62%,8.30%,-13.68%,-15.02%
35,支付宝支付,09-02,349000.0,1527,514,228.55,678.99,5.65%,-1.29%,-6.20%,7.03%,12.63%
36,支付宝支付,09-03,411500.0,1584,521,259.79,789.83,17.91%,3.73%,1.36%,13.67%,16.32%
37,支付宝支付,09-04,355200.0,1530,516,232.16,688.37,-13.68%,-3.41%,-0.96%,-10.64%,-12.85%
38,支付宝支付,09-05,335350.0,1533,509,218.75,658.84,-5.59%,0.20%,-1.36%,-5.78%,-4.29%
39,支付宝支付,09-06,291200.0,1469,495,198.23,588.28,-13.17%,-4.17%,-2.75%,-9.38%,-10.71%
40,银行卡支付,08-30,38500.0,44,24,875.00,1604.17,-86.78%,-97.00%,-95.15%,341.41%,172.69%
41,银行卡支付,08-31,33500.0,45,29,744.44,1155.17,-12.99%,2.27%,20.83%,-14.92%,-27.99%
42,银行卡支付,09-01,82000.0,86,45,953.49,1822.22,144.78%,91.11%,55.17%,28.08%,57.74%
43,银行卡支付,09-02,47500.0,51,29,931.37,1637.93,-42.07%,-40.70%,-35.56%,-2.32%,-10.11%
44,银行卡支付,09-03,44500.0,47,28,946.81,1589.29,-6.32%,-7.84%,-3.45%,1.66%,-2.97%
45,银行卡支付,09-04,41000.0,45,23,911.11,1782.61,-7.87%,-4.26%,-17.86%,-3.77%,12.16%
46,银行卡支付,09-05,72000.0,65,39,1107.69,1846.15,75.61%,44.44%,69.57%,21.58%,3.56%
47,银行卡支付,09-06,100500.0,70,31,1435.71,3241.94,39.58%,7.69%,-20.51%,29.61%,75.61%

In [50]:
pivot_t.to_csv('C:\\Users\\buche\\Desktop\\travail_workspace\\top_up_analysis\\top_up_report\\7days_top_up_pivot_'+ data_day +'.csv', encoding = 'utf-8-sig')
# pivot_t.to_csv('D:\\Desktop\\travail_workspace\\top_up_anaylsis\\top_up_report\\7days_top_up_pivot_'+ data_day +'.csv', encoding = 'utf-8-sig')