# 「潛在」成長比較分析

In [46]:
import pandas as pd
# 生成 series_data_month 系列 訂單時間_年份 訂單時間_月份 利潤
all_data = pd.read_csv('D:/user/anaconda workspace/HahowPython 行銷資料科學/章節 4-1 到 4-7 -【Python銷售資料處理實戰練習】/sales_data.csv')

In [47]:
all_data['profit'] = all_data['單價'] - all_data['成本']

In [48]:
series_data_month = all_data[['系列', '訂單時間', 'profit']]

In [49]:
series_data_month

           系列                 訂單時間   profit
0         系列4  2016-01-01T03:19:35  248.395
1         系列4  2016-01-01T03:19:35  166.145
2         系列4  2016-01-01T03:19:35  297.745
3         系列4  2016-01-01T03:19:35  220.430
4         系列4  2016-01-01T03:19:35  261.555
...       ...                  ...      ...
353219  系列207  2019-11-12T14:44:14  172.725
353220  系列207  2019-11-13T09:37:06  172.725
353221  系列207  2019-11-14T18:34:45  172.725
353222  系列207  2019-11-14T18:34:45  172.725
353223  系列207  2019-11-15T12:14:25  172.725

[353224 rows x 3 columns]

In [50]:
import datetime as dt
series_data_month['訂單時間'] = pd.to_datetime(series_data_month['訂單時間'])
series_data_month['訂單時間_年份'] = series_data_month['訂單時間'].dt.year
series_data_month['訂單時間_月份'] = series_data_month['訂單時間'].dt.to_period('M')

C:\Users\chanm\AppData\Local\Temp\ipykernel_25644\1234783840.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_25644\1234783840.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_25644\1234783840.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [51]:
series_data_month = series_data_month[['系列', '訂單時間_年份', '訂單時間_月份', 'profit']]

In [52]:
series_data_month

           系列  訂單時間_年份  訂單時間_月份   profit
0         系列4     2016  2016-01  248.395
1         系列4     2016  2016-01  166.145
2         系列4     2016  2016-01  297.745
3         系列4     2016  2016-01  220.430
4         系列4     2016  2016-01  261.555
...       ...      ...      ...      ...
353219  系列207     2019  2019-11  172.725
353220  系列207     2019  2019-11  172.725
353221  系列207     2019  2019-11  172.725
353222  系列207     2019  2019-11  172.725
353223  系列207     2019  2019-11  172.725

[353224 rows x 4 columns]

In [53]:
series_data_month = series_data_month.groupby(['系列', '訂單時間_年份', '訂單時間_月份'], as_index = False)['profit'].sum()

In [54]:
series_data_month

          系列  訂單時間_年份  訂單時間_月份      profit
0        系列1     2016  2016-01   55508.880
1        系列1     2016  2016-02  340967.375
2        系列1     2016  2016-03   73574.270
3        系列1     2016  2016-04   80741.535
4        系列1     2016  2016-05   86288.475
...      ...      ...      ...         ...
11109  系列995     2016  2016-05     516.530
11110  系列996     2016  2016-03     551.075
11111  系列997     2017  2017-11     516.530
11112  系列998     2016  2016-02     472.115
11113  系列999     2016  2016-08     245.105

[11114 rows x 4 columns]

In [55]:
series_data_month.to_csv('series_data_month.csv', encoding='utf-8-sig')

# 試做系列3的利潤成長率

In [11]:
series_data_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11114 entries, 0 to 11113
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   系列       11114 non-null  object
 1   訂單時間_年份  11114 non-null  int64
 2   訂單時間_月份  11114 non-null  period[M]
 3   profit   11114 non-null  float64
dtypes: float64(1), int64(1), object(1), period[M](1)
memory usage: 347.4+ KB

In [56]:
# 選出系列3
series_data_month_growth = series_data_month[series_data_month['系列'] == '系列3']

In [57]:
series_data_month_growth.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 5373 to 5405
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   系列       33 non-null     object
 1   訂單時間_年份  33 non-null     int64
 2   訂單時間_月份  33 non-null     period[M]
 3   profit   33 non-null     float64
dtypes: float64(1), int64(1), object(1), period[M](1)
memory usage: 1.3+ KB

In [14]:
# '訂單時間_年份'先轉為str
#series_data_month_growth['訂單時間_年份'] = series_data_month_growth['訂單時間_年份'].astype('int')

In [58]:
# 篩選2018、2019年
series_data_month_growth = series_data_month_growth[series_data_month_growth['訂單時間_年份'] >= 2018]

In [59]:
series_data_month_growth

       系列  訂單時間_年份  訂單時間_月份       profit
5383  系列3     2018  2018-01   433429.535
5384  系列3     2018  2018-02   513212.035
5385  系列3     2018  2018-03   110624.605
5386  系列3     2018  2018-04    91085.295
5387  系列3     2018  2018-05    62600.475
5388  系列3     2018  2018-06   105633.675
5389  系列3     2018  2018-07   170102.870
5390  系列3     2018  2018-08   115171.385
5391  系列3     2018  2018-09    37981.405
5392  系列3     2018  2018-10    41896.505
5393  系列3     2018  2018-11  1973985.195
5394  系列3     2018  2018-12   230803.370
5395  系列3     2019  2019-01   563544.100
5396  系列3     2019  2019-02   256131.435
5397  系列3     2019  2019-03   100017.645
5398  系列3     2019  2019-04   114990.435
5399  系列3     2019  2019-05   251846.210
5400  系列3     2019  2019-06   535980.480
5401  系列3     2019  2019-07   208421.500
5402  系列3     2019  2019-08   116470.935
5403  系列3     2019  2019-09   117660.270
5404  系列3     2019  2019-10    73924.655
5405  系列3     2019  2019-11    44281.755

In [95]:
# 測試看看有無前一年份可比較 條件true or false
now = series_data_month_growth[series_data_month_growth['訂單時間_年份'] == 2019]
past = series_data_month_growth[series_data_month_growth['訂單時間_年份'] == 2018]

KeyError: '訂單時間_年份'

In [63]:
len(past)

12

In [64]:
if len(now) == len(past):
    print('有初始年份可以比較!')
else:
    print('注意資料不全')

注意資料不全

In [65]:
series_data_month_growth

       系列  訂單時間_年份  訂單時間_月份       profit
5383  系列3     2018  2018-01   433429.535
5384  系列3     2018  2018-02   513212.035
5385  系列3     2018  2018-03   110624.605
5386  系列3     2018  2018-04    91085.295
5387  系列3     2018  2018-05    62600.475
5388  系列3     2018  2018-06   105633.675
5389  系列3     2018  2018-07   170102.870
5390  系列3     2018  2018-08   115171.385
5391  系列3     2018  2018-09    37981.405
5392  系列3     2018  2018-10    41896.505
5393  系列3     2018  2018-11  1973985.195
5394  系列3     2018  2018-12   230803.370
5395  系列3     2019  2019-01   563544.100
5396  系列3     2019  2019-02   256131.435
5397  系列3     2019  2019-03   100017.645
5398  系列3     2019  2019-04   114990.435
5399  系列3     2019  2019-05   251846.210
5400  系列3     2019  2019-06   535980.480
5401  系列3     2019  2019-07   208421.500
5402  系列3     2019  2019-08   116470.935
5403  系列3     2019  2019-09   117660.270
5404  系列3     2019  2019-10    73924.655
5405  系列3     2019  2019-11    44281.755

In [19]:
series_data_month_growth.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 5383 to 5405
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   系列       23 non-null     object
 1   訂單時間_年份  23 non-null     int64
 2   訂單時間_月份  23 non-null     period[M]
 3   profit   23 non-null     float64
dtypes: float64(1), int64(1), object(1), period[M](1)
memory usage: 920.0+ bytes

In [20]:
# 如何切出月份 series_data_month_growth['月份'] =
# 先轉成str
series_data_month_growth['訂單時間_月份'] = series_data_month_growth['訂單時間_月份'].astype(str)

In [21]:
series_data_month_growth['月份'] = series_data_month_growth['訂單時間_月份'].str.split('-', expand = True)[1]

In [22]:
# 將「訂單時間_年份」轉換成pivot

series_data_month_growth = series_data_month_growth.pivot(index = ['月份', '系列'], columns = '訂單時間_年份', values = 'profit')

In [23]:
series_data_month_growth

訂單時間_年份         2018        2019
月份 系列
01 系列3    433429.535  563544.100
02 系列3    513212.035  256131.435
03 系列3    110624.605  100017.645
04 系列3     91085.295  114990.435
05 系列3     62600.475  251846.210
06 系列3    105633.675  535980.480
07 系列3    170102.870  208421.500
08 系列3    115171.385  116470.935
09 系列3     37981.405  117660.270
10 系列3     41896.505   73924.655
11 系列3   1973985.195   44281.755
12 系列3    230803.370         NaN

In [24]:
from operator import index
series_data_month_growth = series_data_month_growth.reset_index()
series_data_month_growth

訂單時間_年份  月份   系列         2018        2019
0        01  系列3   433429.535  563544.100
1        02  系列3   513212.035  256131.435
2        03  系列3   110624.605  100017.645
3        04  系列3    91085.295  114990.435
4        05  系列3    62600.475  251846.210
5        06  系列3   105633.675  535980.480
6        07  系列3   170102.870  208421.500
7        08  系列3   115171.385  116470.935
8        09  系列3    37981.405  117660.270
9        10  系列3    41896.505   73924.655
10       11  系列3  1973985.195   44281.755
11       12  系列3   230803.370         NaN

In [25]:
series_data_month_growth = series_data_month_growth.rename(columns = {'2018':'2018年', '2019':'2019年'})

In [26]:
series_data_month_growth.columns

Index(['月份', '系列', 2018, 2019], dtype='object', name='訂單時間_年份')

In [27]:
series_data_month_growth = round(series_data_month_growth)

In [28]:
# 各月份年增成長
series_data_month_growth['年增成長'] = (series_data_month_growth['2019年']-series_data_month_growth['2018年'])/series_data_month_growth['2018年']

KeyError: '2019年'

In [ ]:
# 年整體成長
print('較去年成長'+ str(round((series_data_month_growth['2019年'][0:10].sum() - series_data_month_growth['2018年'][0:10].sum())/ series_data_month_growth['2018年'][0:10].sum()*100)) + '%')

In [ ]:
# 計算「總年增成長率」：了解今年比較去年來說，增長了多少
series_data_month_growth['總年增成長率'] = (series_data_month_growth['2019年'][0:10].sum() - series_data_month_growth['2018年'][0:10].sum())/ series_data_month_growth['2018年'][0:10].sum()

In [ ]:
# 去年11月開始便沒有資料，所以只取到10月
series_data_month_growth = series_data_month_growth[0:10]

In [ ]:
series_data_month_growth

In [ ]:
# 匯出series_data_month_growth
series_data_month_growth.to_csv( 'Top_高獲利系列3_「潛在」成長比較分析表.csv', encoding='utf-8-sig')

# 「潛在」成長比較分析圖

In [ ]:
import plotly.express as px
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
#rank = 1 
series = '系列3'
# 再次繪製折線圖：
fig = px.line(series_data_month_growth, 
            x="月份", 
            y="年增成長", 
            #   color = '訂單時間_年份',
            title ='Top_高獲利系列_「' + series + '」_「潛在」成長比較分析圖')

# 如何加入背景元素（layout）
fig.update_layout(
                title={
                    'text':  'Top' +  str(rank) +'_高獲利系列_「' + series + '」_「潛在」成長比較分析圖',
                    'y':0.9,
                    'x':0.5,
                    'xanchor': 'center',
                    'yanchor': 'top'},
                xaxis_title='月份',
                yaxis_title='年增成長')
fig.update_traces(mode="lines+markers")
plot(fig, filename = 'Top_高獲利系列_「' + series + '」_「潛在」成長比較分析圖.html')

#rank = rank +1

# 製作「潛在」成長比較分析function
做不出來 可能是 series_data_month 格式問題

In [63]:
# 原始資料series_data_month為各系列在每個月分的獲利表
import pandas as pd
series_data_month = pd.read_csv('D:/user/anaconda workspace/HahowPython 行銷資料科學/章節 4-1 到 4-7 -【Python銷售資料處理實戰練習】/series_data_month.csv')

In [64]:
series_data_month

       Unnamed: 0     系列  訂單時間_年份  訂單時間_月份      profit
0               0    系列1     2016  2016-01   55508.880
1               1    系列1     2016  2016-02  340967.375
2               2    系列1     2016  2016-03   73574.270
3               3    系列1     2016  2016-04   80741.535
4               4    系列1     2016  2016-05   86288.475
...           ...    ...      ...      ...         ...
11109       11109  系列995     2016  2016-05     516.530
11110       11110  系列996     2016  2016-03     551.075
11111       11111  系列997     2017  2017-11     516.530
11112       11112  系列998     2016  2016-02     472.115
11113       11113  系列999     2016  2016-08     245.105

[11114 rows x 5 columns]

In [65]:
series_data_month[series_data_month['系列']=='系列3']

      Unnamed: 0   系列  訂單時間_年份  訂單時間_月份       profit
5373        5373  系列3     2017  2017-03   597561.055
5374        5374  系列3     2017  2017-04   882062.160
5375        5375  系列3     2017  2017-05   172040.680
5376        5376  系列3     2017  2017-06   200305.070
5377        5377  系列3     2017  2017-07   156620.450
5378        5378  系列3     2017  2017-08   117173.350
5379        5379  系列3     2017  2017-09   107250.710
5380        5380  系列3     2017  2017-10   109621.155
5381        5381  系列3     2017  2017-11    69591.725
5382        5382  系列3     2017  2017-12    90731.620
5383        5383  系列3     2018  2018-01   433429.535
5384        5384  系列3     2018  2018-02   513212.035
5385        5385  系列3     2018  2018-03   110624.605
5386        5386  系列3     2018  2018-04    91085.295
5387        5387  系列3     2018  2018-05    62600.475
5388        5388  系列3     2018  2018-06   105633.675
5389        5389  系列3     2018  2018-07   170102.870
5390        5390  系列3     2018  2018-08   115171.385
5391        5391  系列3     2018  2018-09    37981.405
5392        5392  系列3     2018  2018-10    41896.505
5393        5393  系列3     2018  2018-11  1973985.195
5394        5394  系列3     2018  2018-12   230803.370
5395        5395  系列3     2019  2019-01   563544.100
5396        5396  系列3     2019  2019-02   256131.435
5397        5397  系列3     2019  2019-03   100017.645
5398        5398  系列3     2019  2019-04   114990.435
5399        5399  系列3     2019  2019-05   251846.210
5400        5400  系列3     2019  2019-06   535980.480
5401        5401  系列3     2019  2019-07   208421.500
5402        5402  系列3     2019  2019-08   116470.935
5403        5403  系列3     2019  2019-09   117660.270
5404        5404  系列3     2019  2019-10    73924.655
5405        5405  系列3     2019  2019-11    44281.755

In [88]:
def potential_growth(data, series, rank, year1, year2):
    import pandas as pd
    import plotly.express as px
    from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
    # 選擇要分析的系列
    series_data_month_growth = series_data_month[series_data_month['系列'] == series]
    # 用年份條件篩選2018, 2019年資料
    series_data_month_growth = series_data_month_growth[series_data_month_growth['訂單時間_年份'] >= int(year1.strip('年'))]

    ###
    # 測試有無前一年份可比較 條件true or false
    #test = len(series_data_month_growth[series_data_month_growth['訂單時間_年份'] == int(year2.strip('年'))]) - len(series_data_month_growth[series_data_month_growth['訂單時間_年份'] == int(year1.strip('年'))])
    #if test == 0:
    #    test == '有初始年份可以比較!'
    #    print('有初始年份可以比較!')
    #elif test > 0:
    #    test = "注意"+ str(year1) +"資料不全"
    #    print("注意"+ str(year1) +"資料不全")
    #elif test < 0:
    #    test = "注意"+ str(year2) +"資料不全"
    #    print("注意"+ str(year2) +"資料不全")
    ###
    
    test = series_data_month_growth[series_data_month_growth['訂單時間_年份']==int(year1.strip('年'))]

    if len(test) ==0:
        print('沒有初始年份可以比較')
        test = '跳過'
        series_data_month_growth = '沒有'
        return series_data_month_growth, test
    else:
        print('有初始年份可以比較!')
        test = '有資料'

    # 切出月份 series_data_month_growth['月份']，先轉成str
    series_data_month_growth['訂單時間_月份'] = series_data_month_growth['訂單時間_月份'].astype(str)
    series_data_month_growth['月份'] = series_data_month_growth['訂單時間_月份'].str.split('-', expand = True)[1]

    # 根據「訂單時間_年份」轉換成pivot
    series_data_month_growth = series_data_month_growth.pivot(index = ['月份', '系列'], columns = '訂單時間_年份', values = 'profit')
    # 格式調整
    series_data_month_growth = series_data_month_growth.reset_index()
    series_data_month_growth = series_data_month_growth.rename(columns={int(year1.strip('年')):year1, int(year2.strip('年')):year2 })
    series_data_month_growth = round(series_data_month_growth)

    # 選資料齊全來計算
    series_data_month_growth = series_data_month_growth[0:10]
    
    # 計算series_data_month_growth['年增成長']和['總年增成長率']
    series_data_month_growth['年增成長'] = round( (series_data_month_growth[year2] - series_data_month_growth[year1] )/ series_data_month_growth[year1], 2)
    series_data_month_growth['總年增成長率'] = (series_data_month_growth[year2][0:10].sum() - series_data_month_growth[year1][0:10].sum())/ series_data_month_growth[year1][0:10].sum()

    

    # 輸出所有series的2018/2019獲利成長比較表
    series_data_month_growth.to_csv( 'Top' +  str(rank) +'_高獲利系列_「' + series + '」_「潛在」成長比較分析表.csv', encoding='utf-8-sig')

    # 繪圖
    # rank = 1 
    # series = '系列3'
    # 再次繪製折線圖：
    fig = px.line(series_data_month_growth, 
                x="月份", 
                y="年增成長", 
                #   color = '訂單時間_年份',
                title ='Top' +  str(rank) +'_高獲利系列_「' + series + '」_「潛在」成長比較分析圖')

    # 如何加入背景元素（layout）
    fig.update_layout(
                    title={
                        'text':  'Top' +  str(rank) +'_高獲利系列_「' + series + '」_「潛在」成長比較分析圖',
                        'y':0.9,
                        'x':0.5,
                        'xanchor': 'center',
                        'yanchor': 'top'},
                    xaxis_title='月份',
                    yaxis_title='年增成長')
    fig.update_traces(mode="lines+markers")
    plot(fig, filename = 'Top' +  str(rank) +'_高獲利系列_「' + series + '」_「潛在」成長比較分析圖.html')

    # rank = rank +1
    return series_data_month_growth, test

In [94]:
series_data_month_growth, test = potential_growth(data=series_data_month, series = '系列3', rank = 3, year1 = '2018年', year2 = '2019年')

有初始年份可以比較!

In [95]:
test

'有資料'

In [91]:
series_data_month_growth, test = potential_growth(data=series_data_month, series = '系列20', rank = 3, year1 = '2018年', year2 = '2019年')

沒有初始年份可以比較

# 製作所有高獲利系列的(總)年增成長比較表

In [97]:
series_data_month_growth_single = series_data_month_growth[['系列', '總年增成長率']]

In [98]:
series_data_month_growth_single

訂單時間_年份   系列    總年增成長率
0        系列3  0.390815
1        系列3  0.390815
2        系列3  0.390815
3        系列3  0.390815
4        系列3  0.390815
5        系列3  0.390815
6        系列3  0.390815
7        系列3  0.390815
8        系列3  0.390815
9        系列3  0.390815

In [99]:
series_data_month_growth_single = series_data_month_growth_single.iloc[0:1, :]

In [100]:
series_data_month_growth_single

訂單時間_年份   系列    總年增成長率
0        系列3  0.390815

In [101]:
profit_data_selected = pd.read_csv('D:/user/anaconda workspace/HahowPython 行銷資料科學/章節 4-1 到 4-7 -【Python銷售資料處理實戰練習】/1_高利潤_貢獻80.0%的高利潤產品組合清單.csv')

In [102]:
profit_data_selected

    Unnamed: 0.1  Unnamed: 0     系列          利潤  利潤佔比  累積利潤佔比  累積產品次數  累積產品佔比
0              0           0    系列1  3832882.90  0.12    0.12       1    0.00
1            103         103    系列2  3201814.84  0.10    0.21       2    0.00
2            183         183    系列3  2338987.66  0.07    0.29       3    0.01
3            104         104   系列20  2281608.42  0.07    0.35       4    0.01
4             44          44   系列14  2230133.08  0.07    0.42       5    0.01
5             34          34   系列13  2222873.70  0.07    0.49       6    0.01
6            191         191   系列32  1146714.69  0.03    0.53       7    0.02
7            262         262   系列45   976465.42  0.03    0.55       8    0.02
8            240         240   系列40   910515.72  0.03    0.58       9    0.02
9            369         369    系列8   905542.89  0.03    0.61      10    0.02
10            86          86   系列18   721812.84  0.02    0.63      11    0.03
11            12          12   系列11   663718.02  0.02    0.65      12    0.03
12           317         317    系列6   542465.07  0.02    0.67      13    0.03
13           355         355   系列73   538194.65  0.02    0.69      14    0.03
14           364         364   系列77   512958.70  0.02    0.70      15    0.04
15           385         385    系列9   463957.44  0.01    0.71      16    0.04
16           239         239    系列4   451835.44  0.01    0.73      17    0.04
17           253         253   系列42   364359.27  0.01    0.74      18    0.04
18           387         387   系列91   345619.43  0.01    0.75      19    0.05
19           395         395   系列95   323893.92  0.01    0.76      20    0.05
20           344         344   系列69   280252.07  0.01    0.77      21    0.05
21           351         351   系列71   275267.72  0.01    0.78      22    0.05
22           175         175   系列29   220704.72  0.01    0.78      23    0.06
23           286         286    系列5   211175.23  0.01    0.79      24    0.06
24            31          31  系列127   205065.70  0.01    0.80      25    0.06
25            55          55   系列15   186669.67  0.01    0.80      26    0.06

In [103]:
# 每一系列的總年增成長率 
series_data_month_growth_all_single = []
# 每一系列的「全部系列「潛在」成長比較分析表」
series_data_month_growth_all = []

rank = 1
for series in profit_data_selected['系列']:
    print(series)
    series_data_month_growth, test = potential_growth(data=series_data_month, series = series, rank = rank, year1 = '2018年', year2 = '2019年')
    rank = rank + 1
    if test == '有資料':
         # 製作總體「潛在」成長比較分析表
        series_data_month_growth_single = series_data_month_growth[['系列', '總年增成長率']]
        series_data_month_growth_single = series_data_month_growth_single.iloc[0:1, :]
        
        # append到series_data_month_growth_all_single中，了解每系列的總年增成長率
        series_data_month_growth_all_single.append(series_data_month_growth_single)
        
        # 另外，合併所有potiential_growth function產出的「潛在」成長比較分析表
        series_data_month_growth_all.append(series_data_month_growth)
    elif test == '跳過':
        print(series, '跳過')

系列1
有初始年份可以比較!
系列2
有初始年份可以比較!
系列3
有初始年份可以比較!
系列20
沒有初始年份可以比較
系列20 跳過
系列14
有初始年份可以比較!
系列13
沒有初始年份可以比較
系列13 跳過
系列32
沒有初始年份可以比較
系列32 跳過
系列45
沒有初始年份可以比較
系列45 跳過
系列40
沒有初始年份可以比較
系列40 跳過
系列8
有初始年份可以比較!
系列18
有初始年份可以比較!
系列11
有初始年份可以比較!
系列6
有初始年份可以比較!
系列73
有初始年份可以比較!
系列77
沒有初始年份可以比較
系列77 跳過
系列9
有初始年份可以比較!
系列4
有初始年份可以比較!
系列42
有初始年份可以比較!
系列91
沒有初始年份可以比較
系列91 跳過
系列95
沒有初始年份可以比較
系列95 跳過
系列69
有初始年份可以比較!
系列71
有初始年份可以比較!
系列29
有初始年份可以比較!
系列5
有初始年份可以比較!
系列127
沒有初始年份可以比較
系列127 跳過
系列15
有初始年份可以比較!

In [104]:
series_data_month_growth_all_single = pd.concat(series_data_month_growth_all_single, axis = 0)

In [105]:
series_data_month_growth_all_single = series_data_month_growth_all_single.sort_values('總年增成長率', ascending=False)

In [106]:
series_data_month_growth_all_single

訂單時間_年份    系列      總年增成長率
0        系列73  221.161866
0        系列14    2.105210
0        系列69    0.900781
0         系列8    0.773422
0         系列3    0.390815
0         系列4   -0.008558
0         系列1   -0.036121
0        系列71   -0.122230
0        系列42   -0.128721
0         系列9   -0.174245
0        系列11   -0.300686
0         系列2   -0.345613
0         系列6   -0.407463
0        系列15   -0.531790
0         系列5   -0.601132
0        系列18   -0.650076
0        系列29   -0.812442

In [107]:
series_data_month_growth_all_single['潛力開發排序'] = range(1, len(series_data_month_growth_all_single)+1)

In [108]:
series_data_month_growth_all_single.to_csv('D:/user/anaconda workspace/HahowPython 行銷資料科學/章節 4-1 到 4-7 -【Python銷售資料處理實戰練習】/0_總體「潛在」成長比較分析.csv', encoding= 'utf-8-sig')

In [109]:
series_data_month_growth_all = pd.concat(series_data_month_growth_all, axis=0)

In [110]:
series_data_month_growth_all.to_csv('D:/user/anaconda workspace/HahowPython 行銷資料科學/章節 4-1 到 4-7 -【Python銷售資料處理實戰練習】/1_全部系列「潛在」成長比較分析表.csv', encoding='utf-8-sig')

In [111]:
#from analysis import move_file
#move_file(dectect_name = '潛在', folder_name = '「潛在」成長比較分析')

# 進行系列「穩定成長」 分析

In [133]:
len(series_data_month_growth_all)

162

In [134]:
series_data_month_growth_all

訂單時間_年份  月份    系列     2018年     2019年  年增成長    總年增成長率
0        01   系列1  354516.0  373260.0  0.05 -0.036121
1        02   系列1  338038.0  386942.0  0.14 -0.036121
2        03   系列1  148785.0  216926.0  0.46 -0.036121
3        04   系列1  165319.0  201720.0  0.22 -0.036121
4        05   系列1  115903.0  688005.0  4.94 -0.036121
..       ..   ...       ...       ...   ...       ...
5        06  系列15   59111.0   25483.0 -0.57 -0.531790
6        07  系列15   71826.0   23076.0 -0.68 -0.531790
7        08  系列15   34066.0   14427.0 -0.58 -0.531790
8        09  系列15   31571.0   21456.0 -0.32 -0.531790
9        10  系列15   27624.0   10977.0 -0.60 -0.531790

[162 rows x 6 columns]

In [135]:
stable_df = series_data_month_growth_all.dropna()

In [136]:
stable_df_tmp = stable_df[stable_df['系列'] == '系列3']

In [137]:
stable_df_tmp

訂單時間_年份  月份   系列     2018年     2019年  年增成長    總年增成長率
0        01  系列3  433430.0  563544.0  0.30  0.390815
1        02  系列3  513212.0  256131.0 -0.50  0.390815
2        03  系列3  110625.0  100018.0 -0.10  0.390815
3        04  系列3   91085.0  114990.0  0.26  0.390815
4        05  系列3   62600.0  251846.0  3.02  0.390815
5        06  系列3  105634.0  535980.0  4.07  0.390815
6        07  系列3  170103.0  208422.0  0.23  0.390815
7        08  系列3  115171.0  116471.0  0.01  0.390815
8        09  系列3   37981.0  117660.0  2.10  0.390815
9        10  系列3   41897.0   73925.0  0.76  0.390815

In [138]:
# 製作「正常年增率」與「穩定指標（標準差）」
# 如果系列中沒有超過9個月的話，即跳過；若超過，則製作
# 新增['正常年增率']：去除缺值後，才具比較標準，計算年增率才公允
# 新增['穩定指標']（標準差）：計算每一個系列年增成長的標準差。若數值低，則成長效果較為穩健

In [139]:
if len(stable_df_tmp) <9:
    print('跳過')

else:
    stable_df_tmp['正常年增率'] = (stable_df_tmp['2019年'].sum() - stable_df_tmp['2018年'].sum())/stable_df_tmp['2018年'].sum()

    stable_df_tmp['穩定指標（標準差）'] = stable_df_tmp['年增成長'].std()

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\1461761086.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\1461761086.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [140]:
stable_df_tmp

訂單時間_年份  月份   系列     2018年     2019年  年增成長    總年增成長率     正常年增率  穩定指標（標準差）
0        01  系列3  433430.0  563544.0  0.30  0.390815  0.390815   1.521741
1        02  系列3  513212.0  256131.0 -0.50  0.390815  0.390815   1.521741
2        03  系列3  110625.0  100018.0 -0.10  0.390815  0.390815   1.521741
3        04  系列3   91085.0  114990.0  0.26  0.390815  0.390815   1.521741
4        05  系列3   62600.0  251846.0  3.02  0.390815  0.390815   1.521741
5        06  系列3  105634.0  535980.0  4.07  0.390815  0.390815   1.521741
6        07  系列3  170103.0  208422.0  0.23  0.390815  0.390815   1.521741
7        08  系列3  115171.0  116471.0  0.01  0.390815  0.390815   1.521741
8        09  系列3   37981.0  117660.0  2.10  0.390815  0.390815   1.521741
9        10  系列3   41897.0   73925.0  0.76  0.390815  0.390815   1.521741

# For迴圈製作每個系列「正常年增率」與「穩定指標（標準差）」的狀況

In [152]:
stable_df['系列'].unique()

array(['系列1', '系列2', '系列3', '系列14', '系列8', '系列11', '系列6', '系列73', '系列9',
       '系列4', '系列42', '系列69', '系列71', '系列29', '系列5', '系列15'], dtype=object)

In [153]:
stable_df_tmp_list = []
for series in stable_df['系列'].unique():
    stable_df_tmp = stable_df[stable_df['系列'] == series]
    
    if len(stable_df_tmp) <9:
        print('跳過')

    else:
        stable_df_tmp['正常年增率'] = (stable_df_tmp['2019年'].sum() - stable_df_tmp['2018年'].sum())/stable_df_tmp['2018年'].sum()
        stable_df_tmp['穩定指標（標準差）'] = stable_df_tmp['年增成長'].std()
        stable_df_tmp_list.append(stable_df_tmp)

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

跳過
跳過
跳過
跳過
跳過
跳過

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chanm\AppData\Local\Temp\ipykernel_30768\89595674.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [154]:
stable_df_final = pd.concat(stable_df_tmp_list, axis = 0)

In [155]:
stable_df_final

訂單時間_年份  月份    系列     2018年     2019年  年增成長    總年增成長率     正常年增率  穩定指標（標準差）
0        01   系列1  354516.0  373260.0  0.05 -0.036121 -0.036121   1.621140
1        02   系列1  338038.0  386942.0  0.14 -0.036121 -0.036121   1.621140
2        03   系列1  148785.0  216926.0  0.46 -0.036121 -0.036121   1.621140
3        04   系列1  165319.0  201720.0  0.22 -0.036121 -0.036121   1.621140
4        05   系列1  115903.0  688005.0  4.94 -0.036121 -0.036121   1.621140
..       ..   ...       ...       ...   ...       ...       ...        ...
5        06  系列15   59111.0   25483.0 -0.57 -0.531790 -0.531790   0.162169
6        07  系列15   71826.0   23076.0 -0.68 -0.531790 -0.531790   0.162169
7        08  系列15   34066.0   14427.0 -0.58 -0.531790 -0.531790   0.162169
8        09  系列15   31571.0   21456.0 -0.32 -0.531790 -0.531790   0.162169
9        10  系列15   27624.0   10977.0 -0.60 -0.531790 -0.531790   0.162169

[100 rows x 8 columns]

In [157]:
stable_df_final.to_csv('2_「穩定」成長比較分析.csv', encoding='utf-8-sig')

# 排序並生成「穩定指標值」 的分析表

In [197]:
stable_df_index = stable_df_final[['系列', '正常年增率', '穩定指標（標準差）']]

In [198]:
stable_df_index

訂單時間_年份    系列     正常年增率  穩定指標（標準差）
0         系列1 -0.036121   1.621140
1         系列1 -0.036121   1.621140
2         系列1 -0.036121   1.621140
3         系列1 -0.036121   1.621140
4         系列1 -0.036121   1.621140
..        ...       ...        ...
5        系列15 -0.531790   0.162169
6        系列15 -0.531790   0.162169
7        系列15 -0.531790   0.162169
8        系列15 -0.531790   0.162169
9        系列15 -0.531790   0.162169

[100 rows x 3 columns]

In [199]:
stable_df_index = stable_df_index.drop_duplicates()

In [200]:
stable_df_index

訂單時間_年份    系列     正常年增率  穩定指標（標準差）
0         系列1 -0.036121   1.621140
0         系列2 -0.345613   0.616102
0         系列3  0.390815   1.521741
0        系列11 -0.300686   0.867897
0         系列6 -0.407463   0.189470
0         系列9 -0.174245   0.727386
0         系列4 -0.008558   1.308572
0        系列29 -0.812442   0.207421
0         系列5 -0.601132   0.133066
0        系列15 -0.531790   0.162169

In [201]:
# 標準差由小至大排序
stable_df_index = stable_df_index.sort_values('穩定指標（標準差）', ascending = False)

In [202]:
# 新增穩定排名
stable_df_index['穩定指標高低'] = range(1, len(stable_df_index)+1)

In [203]:
# ['穩定指標值'] = 正常年增率	* '穩定指標高低'
stable_df_index['穩定指標值'] = stable_df_index['正常年增率'] * stable_df_index['穩定指標高低']

In [204]:
# 由大至小排序
stable_df_index = stable_df_index.sort_values('穩定指標值', ascending = False)

In [205]:
# 再排名
stable_df_index['建議參考順序'] = range(1, len(stable_df_index)+1)

In [206]:
stable_df_index

訂單時間_年份    系列     正常年增率  穩定指標（標準差）  穩定指標高低     穩定指標值  建議參考順序
0         系列3  0.390815   1.521741       2  0.781631       1
0         系列4 -0.008558   1.308572       3 -0.025673       2
0         系列1 -0.036121   1.621140       1 -0.036121       3
0         系列9 -0.174245   0.727386       5 -0.871224       4
0        系列11 -0.300686   0.867897       4 -1.202744       5
0         系列2 -0.345613   0.616102       6 -2.073677       6
0         系列6 -0.407463   0.189470       8 -3.259706       7
0        系列15 -0.531790   0.162169       9 -4.786113       8
0        系列29 -0.812442   0.207421       7 -5.687091       9
0         系列5 -0.601132   0.133066      10 -6.011321      10

In [208]:
stable_df_index.to_csv('3_「穩定」成長比較分析_個別系列建議參考順序表.csv', encoding='utf-8-sig' )

# 可以再做其他非高獲利系列的分析，是否獲利也穩定成長

# 是否高獲利系列面臨成長衰退??

# 可以增加 是否為高獲利(80%)系列 yes or no